name: gestion_stock_clientes
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  cloud_firestore: ^4.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
