// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUzFCke9eedHFCIOskpthwFewe7rLk7GM',
    appId: '1:253165065100:web:2934a9e979f1e031ec7ca9',
    messagingSenderId: '253165065100',
    projectId: 'gestion-stock-clientes',
    authDomain: 'gestion-stock-clientes.firebaseapp.com',
    storageBucket: 'gestion-stock-clientes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAKlk-xkS_Y8bW41Vg-RztXtL15is8goU',
    appId: '1:253165065100:android:fd1ca82f4847bd40ec7ca9',
    messagingSenderId: '253165065100',
    projectId: 'gestion-stock-clientes',
    storageBucket: 'gestion-stock-clientes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYxbPwxnodLJBsw52H2sz4hLob71yWAlQ',
    appId: '1:253165065100:ios:8e591e3ceac64691ec7ca9',
    messagingSenderId: '253165065100',
    projectId: 'gestion-stock-clientes',
    storageBucket: 'gestion-stock-clientes.appspot.com',
    iosBundleId: 'com.example.gestionStockClientes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYxbPwxnodLJBsw52H2sz4hLob71yWAlQ',
    appId: '1:253165065100:ios:9c32666b60d4b5e5ec7ca9',
    messagingSenderId: '253165065100',
    projectId: 'gestion-stock-clientes',
    storageBucket: 'gestion-stock-clientes.appspot.com',
    iosBundleId: 'com.example.gestionStockClientes.RunnerTests',
  );
}
